### ISSUE TITLE
Building JAR

### ISSUE THREAD

**Issue by miiihi** [csowada/org.eclipse.smarthome.automation.module.script.jsext#1]
Hi,

I'm trying to build a JAR file from the repo and failing. 
Using Maven, build reports multiple missing dependencies. I tried to resolve and add them myself, but couldn't locate all of them... 
What would be the simplest way to build the JAR?

I'm an Angular developer, with lots of Typescript experiences, but with very limited Java experience.

Thanks

**Comment by csowada** [comment]
This version is not working with openhab 2.5. I've prepared a new version yesterday. But to get it compiled do following steps with the new version. With v2.4 it is similar, but it is the eclipse smarthome core project required.

- Clone the openhab-core repo
- Switch to Tag 2.5
- Clone this project into the ``bundles" directory
- Add the the project to the ``pom.xml`` with ``<module>org.openhab.core.automation.module.script.jsext</module>`` in the ``bundles`` directory
- Run ``mvn install`` from the ``org.openhab.core.automation.module.script.jsext`` folder
- Maybe it is required to run ``mvn install`` from the root directory first

**Comment by miiihi** [comment]
Hi,

thanks for the quick reply. All steps seem clear, except for the versions. 

You're saying that "**This** version is not working with openhab 2.5" but later you're saying that I need to switch to openhab-core Tag 2.5 and "Clone **this** project into the ``bundles" directory"

Anyway, I tried openHab 2.5 (as I'm using 2.5) with this repository, but it's failing...

So, can you push your changes for the version 2.5  or is it a separate repository?

Thanks

**Comment by csowada** [comment]
So, the new version has been released. You can download it from the releases or compile it from the sources.

https://github.com/csowada/org.eclipse.smarthome.automation.module.script.jsext/releases/tag/v2.5.0

**Comment by miiihi** [comment]
@csowada Thank you very much!
I was able to compile my own version without any issues. Installed the JAR and it's working fine...

One more question though - do you maybe have any plans to release this addon as "official" OpenHab module? Or to maybe implement the required changes in the "official" rule engine addon?

**Comment by csowada** [comment]
@miiihi , you have see the compiled jar file in the release section?

I think for a release we need more feedback from the community. My extension works for me, but I don't know if anybody else expect you is using the extension. But for me it is the best solution because I'm focused on JS and TypeScript at work. And I don't like the default rule engine.
Maybe the second issue could be the ``require`` library and it's licence. It is maybe not compatible with epl v2.

**Comment by miiihi** [comment]
@csowada yes, I have seen the jar in releases, but wanted to try the build myself anyway.

My reason that brought me to your addon was exactly the same - "I'm focused on JS and TypeScript at work. And I don't like the default rule engine." You made me very happy when I found your addon :) 
Regarding license, the require lib is [MIT](https://github.com/malaporte/nashorn-commonjs-modules/blob/master/LICENSE) licensed, so that shouldn't be a problem. Anyway, if you'll decide for publishing I can offer help with testing or preparing a starter lib...
